server:
  port: 9090
eureka:
  instance:
    hostname: servicediscovery-dev-karthick3.sandbox-ocp43-one-176292-be5b1ee812fa4041cc73b6bbf969fc88-0000.eu-gb.containers.appdomain.cloud
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}/eureka/
spring:
  data:
    mongodb:
      database: Hackathon
      host: 172.21.157.96
      port: 27017
      username: root
      password: root
  cloud:
    config:
      uri: https://configserverservice-dev-karthick3.sandbox-ocp43-one-176292-be5b1ee812fa4041cc73b6bbf969fc88-0000.eu-gb.containers.appdomain.cloud
      username: root
      password: s3cr3t
